from __future__ import annotations

import json
import hashlib
import mimetypes
import re
import time
from pathlib import Path
from urllib.parse import quote, urlencode, urljoin
from urllib.request import Request, urlopen

from openpyxl import load_workbook


LABEL_DIR = Path(__file__).resolve().parent
SOURCE = LABEL_DIR / "원내보유의약품리스트.xlsx"
OUTPUT = LABEL_DIR / "data" / "hospitalDrugLabels.generated.json"
MARKDOWN_OUTPUT_DIR = LABEL_DIR / "원내보유의약품리스트 마크다운"
SIDE_LABEL_TEMPLATE = LABEL_DIR / "뺑뺑이 PTP통, 병_측면라벨_양식.xlsx"
IMAGE_OUTPUT_DIR = LABEL_DIR.parent / "public" / "pharmacy-drug-images"
RULE_SHEET_NAMES = ["라벨 생성규칙", "경구 주사 리스트", "영양수액리스트", "외용제리스트", "시럽리스트"]
HEALTH_SEARCH_URL = "https://health.kr/searchDrug/search_detail.asp"
HEALTH_POPUP_URL = "https://health.kr/searchDrug/ajax/ajax_result_pop.asp"
HEALTH_HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}


def clean(value: object) -> str:
    if value is None:
        return ""
    return str(value).replace("_x000D_", "").strip()


def is_yes(value: object) -> bool:
    return clean(value).upper() == "Y"


def normalized_name(value: object) -> str:
    return re.sub(r"[^0-9a-z가-힣]", "", clean(value).lower())


def normalized_core_name(value: object) -> str:
    text = clean(value).lower()
    text = re.sub(r"\d+(?:\.\d+)?\s*(?:mcg|μg|mg|g|ml|iu|%)(?:/\d+(?:\.\d+)?\s*(?:ml|g))?", "", text)
    text = re.sub(r"\b(?:tab(?:let)?|cap(?:sule)?|inj(?:ection)?|syr(?:up)?|solution|soln|정|캡슐|주|시럽|액)\b", "", text)
    return re.sub(r"[^0-9a-z가-힣]", "", text)


def markdown_cell(value: object) -> str:
    return clean(value).replace("|", "\\|").replace("\n", "<br>")


def write_rule_markdowns(workbook) -> None:
    MARKDOWN_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for sheet_name in RULE_SHEET_NAMES:
        worksheet = workbook[sheet_name]
        raw_rows = [[clean(value) for value in row] for row in worksheet.iter_rows(values_only=True)]
        max_column = max((index + 1 for row in raw_rows for index, value in enumerate(row) if clean(value)), default=1)
        rows = [row[:max_column] for row in raw_rows if any(clean(value) for value in row[:max_column])]
        columns = ["행", *[chr(ord("A") + index) for index in range(max_column)]]
        lines = [
            f"# {sheet_name}",
            "",
            "- Source workbook: `원내보유의약품리스트.xlsx`",
            f"- Source sheet: `{sheet_name}`",
            "- Generated by `약제팀 라벨/extract_hospital_labels.py`.",
            "",
            "| " + " | ".join(columns) + " |",
            "| " + " | ".join(["---"] * len(columns)) + " |",
        ]
        for row_number, row in enumerate(rows, start=1):
            padded = row + [""] * (max_column - len(row))
            lines.append("| " + " | ".join([str(row_number), *[markdown_cell(value) for value in padded]]) + " |")
        (MARKDOWN_OUTPUT_DIR / f"{sheet_name}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def extract_side_label_images() -> dict[str, str]:
    if not SIDE_LABEL_TEMPLATE.exists():
        return {}
    workbook = load_workbook(SIDE_LABEL_TEMPLATE, data_only=True)
    IMAGE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    image_by_name: dict[str, str] = {}
    for worksheet in workbook.worksheets:
        for image in worksheet._images:
            anchor_row = image.anchor._from.row + 1
            name_column = image.anchor._from.col + 2
            label_text = ""
            for row_number in range(max(1, anchor_row - 2), min(worksheet.max_row, anchor_row + 3) + 1):
                candidate = clean(worksheet.cell(row_number, name_column).value)
                if candidate:
                    label_text = candidate
                    break
            if not label_text:
                continue
            names = [part.strip("() ") for part in label_text.splitlines()[:2] if part.strip()]
            if not names:
                continue
            data = image._data()
            extension = image.format.lower() if image.format else "png"
            digest = hashlib.sha1(data).hexdigest()[:16]
            file_name = f"{digest}.{extension}"
            target = IMAGE_OUTPUT_DIR / file_name
            if not target.exists():
                target.write_bytes(data)
            public_path = f"/pharmacy-drug-images/{file_name}"
            for name in names:
                image_by_name[normalized_name(name)] = public_path
                core_name = normalized_core_name(name)
                if len(core_name) >= 4:
                    image_by_name.setdefault(core_name, public_path)
    return image_by_name


def match_image(image_by_name: dict[str, str], *names: str) -> str:
    normalized = [normalized_name(name) for name in names if clean(name)]
    normalized += [normalized_core_name(name) for name in names if len(normalized_core_name(name)) >= 4]
    for name in normalized:
        if name in image_by_name:
            return image_by_name[name]
    candidates = [
        (len(image_name), image_path)
        for image_name, image_path in image_by_name.items()
        if len(image_name) >= 4 and any(image_name in name or name in image_name for name in normalized)
    ]
    return max(candidates, default=(0, ""))[1]


def row_value(row: tuple[object, ...], index: int) -> str:
    return clean(row[index]) if index < len(row) else ""


def normalize_cabinet_warning(value: object) -> str:
    text = clean(value)
    return "PTP" if text.upper() == "T" else text


def cabinet_info(source: str, **values: str) -> dict[str, str]:
    result = {"source": source}
    result.update({key: value for key, value in values.items() if clean(value)})
    return result


def read_cabinet_oral_injection_entries(worksheet) -> dict[str, dict[str, str]]:
    entries: dict[str, dict[str, str]] = {}
    for row in worksheet.iter_rows(min_row=2, values_only=True):
        for offset in (0, 4, 8):
            name = row_value(row, offset + 1)
            if not name:
                continue
            entries[name.lower()] = cabinet_info(
                "경구 주사 리스트",
                atc=row_value(row, offset),
                warning=normalize_cabinet_warning(row_value(row, offset + 2)),
                expiry=row_value(row, offset + 3),
            )
    return entries


def read_cabinet_nutrition_entries(worksheet) -> dict[str, dict[str, str]]:
    entries: dict[str, dict[str, str]] = {}
    for row in worksheet.iter_rows(min_row=2, values_only=True):
        name = row_value(row, 0)
        if not name:
            continue
        locations = list(dict.fromkeys(row_value(row, index) for index in range(2, len(row)) if row_value(row, index)))
        entries[name.lower()] = cabinet_info(
            "영양수액리스트",
            warning=normalize_cabinet_warning(row_value(row, 1)),
            location=" / ".join(locations),
        )
    return entries


def read_cabinet_code_entries(worksheet, source: str) -> dict[str, dict[str, str]]:
    entries: dict[str, dict[str, str]] = {}
    for row in worksheet.iter_rows(min_row=2, values_only=True):
        code = row_value(row, 0)
        if not code:
            continue
        entries[code] = cabinet_info(source, location=row_value(row, 2))
    return entries


def read_with_retries(request: Request, timeout: int = 30, attempts: int = 3) -> tuple[bytes, str]:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            with urlopen(request, timeout=timeout) as response:
                return response.read(), response.headers.get("Content-Type", "")
        except Exception as error:
            last_error = error
            if attempt + 1 < attempts:
                time.sleep(1 + attempt)
    raise last_error or RuntimeError("request failed")


def health_request(url: str, data: bytes | None = None) -> bytes:
    request = Request(url, data=data, headers=HEALTH_HEADERS)
    return read_with_retries(request)[0]


def health_search_terms(korean_name: str, common_name: str) -> list[str]:
    terms = [korean_name, common_name]
    for value in [korean_name, common_name]:
        stripped = re.sub(r"^\s*\[(마약|향정)\]\s*", "", clean(value))
        stripped = re.sub(r"\s+\d+(?:\.\d+)?\s*(?:mcg|μg|mg|g|ml|iu|%)\b.*$", "", stripped, flags=re.I)
        if stripped and stripped not in terms:
            terms.append(stripped)
    return [term for term in terms if clean(term)]


def find_health_drug_code(korean_name: str, common_name: str) -> str:
    for term in health_search_terms(korean_name, common_name):
        body = urlencode({"search_detail": "Y", "input_drug_nm": term, "movefrom": "drug"}).encode("utf-8")
        html = health_request(HEALTH_SEARCH_URL, body).decode("utf-8", errors="ignore")
        match = re.search(r"drug_detailHref\('([^']+)'\)", html)
        if match:
            return match.group(1)
    return ""


def image_extension(url: str, content_type: str) -> str:
    suffix = Path(url.split("?", 1)[0]).suffix.lower()
    if suffix in {".jpg", ".jpeg", ".png", ".gif", ".webp"}:
        return suffix.lstrip(".")
    guessed = mimetypes.guess_extension(content_type.split(";", 1)[0].strip())
    return (guessed or ".jpg").lstrip(".")


def health_image_url_candidates(url: str) -> list[str]:
    normalized = urljoin("https://health.kr", url.replace("\\/", "/"))
    candidates = [normalized]
    marker = "/images/ext_images/"
    if marker in normalized:
        candidates.append("https://common.health.kr/shared" + normalized.split("health.kr:443", 1)[-1])
        candidates.append("https://common.health.kr/shared" + normalized.split("health.kr", 1)[-1])
    return list(dict.fromkeys(candidates))


def fetch_health_image(korean_name: str, common_name: str) -> tuple[str, str]:
    try:
        drug_code = find_health_drug_code(korean_name, common_name)
        if not drug_code:
            return "", f"{HEALTH_SEARCH_URL}?search_detail=Y&input_drug_nm={quote(korean_name)}"
        popup_url = f"{HEALTH_POPUP_URL}?drug_cd={quote(drug_code)}"
        payload = health_request(popup_url).decode("utf-8", errors="ignore")
        data = json.loads(payload)
        if not data:
            return "", f"https://health.kr/searchDrug/result_drug.asp?drug_cd={quote(drug_code)}"
        image_urls = [url for url in clean(data[0].get("drug_pic", "")).split("|") if url]
        if not image_urls:
            return "", f"https://health.kr/searchDrug/result_drug.asp?drug_cd={quote(drug_code)}"
        preferred_urls = [image_urls[1], image_urls[0]] if len(image_urls) > 1 else image_urls
        image_data = b""
        image_url = ""
        extension = "jpg"
        for candidate_url in preferred_urls:
            for resolved_url in health_image_url_candidates(candidate_url):
                try:
                    image_url = resolved_url
                    image_request = Request(image_url, headers=HEALTH_HEADERS)
                    image_data, content_type = read_with_retries(image_request, timeout=45)
                    extension = image_extension(image_url, content_type)
                    break
                except Exception:
                    image_data = b""
            if image_data:
                break
        if not image_data:
            return "", f"https://health.kr/searchDrug/result_drug.asp?drug_cd={quote(drug_code)}"
        digest = hashlib.sha1(image_data).hexdigest()[:16]
        file_name = f"health-{drug_code.lower()}-{digest}.{extension}"
        target = IMAGE_OUTPUT_DIR / file_name
        IMAGE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_bytes(image_data)
        return f"/pharmacy-drug-images/{file_name}", f"https://health.kr/searchDrug/result_drug.asp?drug_cd={quote(drug_code)}"
    except Exception as error:
        print(f"Skipping health.kr image for {common_name}: {error}")
        return "", f"{HEALTH_SEARCH_URL}?search_detail=Y&input_drug_nm={quote(korean_name)}"


def main() -> None:
    image_by_name = extract_side_label_images()
    workbook = load_workbook(SOURCE, data_only=True, read_only=True)
    write_rule_markdowns(workbook)
    worksheet = workbook.worksheets[0]
    oral_injection_entries = read_cabinet_oral_injection_entries(workbook["경구 주사 리스트"])
    nutrition_entries = read_cabinet_nutrition_entries(workbook["영양수액리스트"])
    external_entries = read_cabinet_code_entries(workbook["외용제리스트"], "외용제리스트")
    syrup_entries = read_cabinet_code_entries(workbook["시럽리스트"], "시럽리스트")
    headers = [clean(value).replace("\n", " ") for value in next(worksheet.iter_rows(min_row=1, max_row=1, values_only=True))]
    index = {header: position for position, header in enumerate(headers)}

    def read(raw: tuple[object, ...], header: str) -> str:
        return clean(raw[index[header]])

    def read_optional(raw: tuple[object, ...], header: str) -> str:
        return clean(raw[index[header]]) if header in index else ""

    rows: list[dict[str, object]] = []
    for raw in worksheet.iter_rows(min_row=2, values_only=True):
        code = read(raw, "약품코드")
        name = read(raw, "상용약품명")
        if not code or not name:
            continue
        korean_name = read(raw, "한글약품명")
        oral_injection_info = oral_injection_entries.get(name.lower())
        nutrition_info = nutrition_entries.get(name.lower())
        external_info = external_entries.get(code)
        syrup_info = syrup_entries.get(code)
        image_path = read_optional(raw, "식별사진경로") or match_image(image_by_name, name, korean_name)
        image_source_url = read_optional(raw, "식별사진출처")
        if not image_path and is_yes(raw[index["3단장 유색 반티통 측면라벨"]]):
            image_path, image_source_url = fetch_health_image(korean_name, name)
        if not image_source_url:
            image_source_url = f"{HEALTH_SEARCH_URL}?search_detail=Y&input_drug_nm={quote(korean_name)}"
        drug_type = read(raw, "약품유형")
        legacy_side_1t = read(raw, "1T 3단장 뺑뺑이 PTP 측면라벨")
        legacy_side_half = read(raw, "0.5T 3단장 뺑뺑이 병 측면라벨")
        legacy_side_quarter = read(raw, "0.25T 3단장 뺑뺑이 병 측면라벨")
        legacy_cap = read(raw, "3단장 유색 반티통 병뚜껑")
        cap_background = read(raw, "3단장 반티통 병뚜껑 바탕색 기호")
        rows.append(
            {
                "code": code,
                "itemCode": read(raw, "물품코드"),
                "name": name,
                "koreanName": korean_name,
                "strength": read(raw, "함량"),
                "drugType": drug_type,
                "fluidColor": read_optional(raw, "일반수액 색기호"),
                "highCost": is_yes(raw[index["고가약"]]),
                "narcotic": is_yes(read_optional(raw, "마약")) or drug_type == "마약",
                "psychotropic": is_yes(read_optional(raw, "향정")) or drug_type == "향정",
                "anticancer": is_yes(read_optional(raw, "항암제")) or drug_type == "항암제" or is_yes(raw[index["경구항암제"]]),
                "eCart": is_yes(read_optional(raw, "E-cart")),
                "eCartNicu": is_yes(read_optional(raw, "E-cart(NICU)")),
                "spec": read(raw, "규격"),
                "package": read(raw, "포장"),
                "storage": read(raw, "보관법"),
                "lightProtected": read(raw, "차광필요") == "차광",
                "inHospital": is_yes(raw[index["원내보유"]]),
                "oralAnticancer": is_yes(raw[index["경구항암제"]]),
                "similarLook": is_yes(raw[index["유사모양"]]),
                "similarSound": is_yes(raw[index["유사발음"]]),
                "doseCaution": is_yes(raw[index["용량주의"]]),
                "doseCheck": is_yes(raw[index["용량확인"]]),
                "highRisk": is_yes(raw[index["고위험의약품"]]),
                "highRiskCategory": read(raw, "고위험의약품분류"),
                "atc": read(raw, "ATC"),
                "ptpOpened": is_yes(raw[index["PTP깐거"]]),
                "inpatientPowderPtp": is_yes(raw[index["입원산제용PTP 깐거"]]),
                "threeTierHalf": is_yes(raw[index["3단반알"]]),
                "expiry": read(raw, "유효기간"),
                "location": read(raw, "위치"),
                "ampouleHolder": read(raw, "앰플꽂이"),
                "sideLabel1T": legacy_side_1t,
                "sideLabelHalfT": legacy_side_half,
                "sideLabelQuarterT": legacy_side_quarter,
                "sideLabel": is_yes(read_optional(raw, "측면라벨")) or any(is_yes(value) for value in [legacy_side_1t, legacy_side_half, legacy_side_quarter]),
                "labelDose1T": is_yes(read_optional(raw, "정제용량 1T")) or is_yes(legacy_side_1t),
                "labelDoseHalfT": is_yes(read_optional(raw, "정제용량 0.5T")) or is_yes(legacy_side_half),
                "labelDoseQuarterT": is_yes(read_optional(raw, "정제용량 0.25T")) or is_yes(legacy_side_quarter),
                "coloredSideLabel": read(raw, "3단장 유색 반티통 측면라벨"),
                "coloredSideBackground": read(raw, "3단장 유색 반티통 측면라벨 바탕색"),
                "capLabel": legacy_cap,
                "regularCapLabel": is_yes(read_optional(raw, "병뚜껑")) or (is_yes(legacy_cap) and not cap_background),
                "coloredCapLabel": is_yes(read_optional(raw, "유색병뚜껑")) or (is_yes(legacy_cap) and bool(cap_background)),
                "capBackground": cap_background,
                "nameCaution": is_yes(raw[index["이름주의"]]),
                "border": is_yes(raw[index["테두리"]]),
                "borderColor": read(raw, "테두리 색기호"),
                "cabinetOralInjection": oral_injection_info is not None,
                "cabinetNutrition": nutrition_info is not None,
                "cabinetExternal": external_info is not None,
                "cabinetSyrup": syrup_info is not None,
                "cabinetOralInjectionInfo": oral_injection_info or None,
                "cabinetNutritionInfo": nutrition_info or None,
                "cabinetExternalInfo": external_info or None,
                "cabinetSyrupInfo": syrup_info or None,
                "imagePath": image_path,
                "imageSourceUrl": image_source_url,
            }
        )

    rows.sort(key=lambda row: (str(row["name"]).lower(), str(row["code"]).lower()))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} hospital drug label rows to {OUTPUT}")


if __name__ == "__main__":
    main()
